/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_i2p_router_MacLauncher */

#ifndef _Included_net_i2p_router_MacLauncher
#define _Included_net_i2p_router_MacLauncher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_i2p_router_MacLauncher
 * Method:    disableAppNap
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_i2p_router_MacLauncher_disableAppNap
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
