
name: Java CI

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: build with script
        run: ./build.sh
      - name: Upload I2P-Easy-Install-Bundle-${{ github.sha }}-unsigned.exe
        uses: actions/upload-artifact@v4
        with:
          name: I2P-EXE-${{ github.sha }}-unsigned.exe
          path: I2P-EXE-2.4.0.exe
        

